---
# To get started with Dependabot version updates,
# you'll need to specify which package ecosystems to
# update and where the package manifests are located.
# https://docs.github.com/code-security/dependabot
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
